spring.application.name=crm-rentacar

# --- CONEXIÓN A LA BASE DE DATOS EN LA NUBE (AIVEN) ---
# Esta es la dirección de tu servidor en Ámsterdam
spring.datasource.url=jdbc:mysql://crm-coches-db-crm-coches.f.aivencloud.com:27736/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
# IMPORTANTE: Borra el texto de abajo y pega la contraseña que copiaste de Aiven (la del icono del ojo)
spring.datasource.password=AVNS_aVa8zdPpwcr8bov12zG

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURACIÓN JPA / HIBERNATE ---
# 'update' hace que Hibernate cree las tablas automáticamente en la nube
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- LÍMITE DE SUBIDA DE FICHEROS (Para las fotos de los coches) ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB